-- Tabla Usuarios
CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(100),
    EMAIL NVARCHAR(100),
    ADICIONADO_POR NVARCHAR(100),
    FECHA_ADICION DATETIME,
    MODIFICADO_POR NVARCHAR(100),
    FECHA_MODIFICACION DATETIME
);

-- Tabla Estudiantes
CREATE TABLE ESTUDIANTES (
    ID INT PRIMARY KEY IDENTITY(1,1),
	IDENTIFICACION NVARCHAR(20),
    NOMBRE NVARCHAR(100),
	PRIMER_APELLIDO NVARCHAR(100),
	SEGUNDO_APELLIDO NVARCHAR(100),
    FECHA_NACIMIENTO DATE,
    ADICIONADO_POR NVARCHAR(100),
    FECHA_ADICION DATETIME,
    MODIFICADO_POR NVARCHAR(100),
    FECHA_MODIFICACION DATETIME,
);

-- Tabla Cursos
CREATE TABLE CURSOS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(100),
    DESCRIPCION NVARCHAR(255), 
    ADICIONADO_POR NVARCHAR(100),
    FECHA_ADICION DATETIME,
    MODIFICADO_POR NVARCHAR(100),
    FECHA_MODIFICACION DATETIME
);

-- Tabla Matricula
CREATE TABLE MATRICULA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    ESTUDIANTE_ID INT,
    CURSO_ID INT,
    FECHA_MATRICULA DATETIME,
    ADICIONADO_POR NVARCHAR(100),
    FECHA_ADICION DATETIME,
    MODIFICADO_POR NVARCHAR(100),
    FECHA_MODIFICACION DATETIME,
    CONSTRAINT FK_MATRICULA_ESTUDIANTE FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTES(ID),
    CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(ID)
);
